### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by sgoudham** [catppuccin-rfc/userstyles#2]
List of stuff we need to do before moving it to the `catppuccin` organisation.

- [x] Update every port's `...user.css` files to reflect the new location of files
	- I believe it's just the fields `@namespace`, `@updateUrl`
- [ ] Create and agree on structure of README
	- [ ] 	Create CONTRIBUTING.md
- [ ] ~~Disregard unnecessary information in each port's README. (e.g stars badge is no longer relevant)~~
	- [ ] ~~(I believe @nekowinston is interested in defining a build system to auto-generate these which ties into the above)~~
- [x] Create issue labels for each port (I really hope there isn't a label limit :sweat_smile:)
- [ ] Check that CODEOWNERS file is accurate

**Comment by nekowinston** [comment]
I think this list covers most of the TODOs. :+1:

> Disregard unnecessary information in each port's README

I'm not even sure that we need a README for each stylesheet, some of them are literally only "press stylus install" and you're done. Whats worth mentioning for *some* ports, like GitHub, is enabling CSP Patching in Stylus.

> I really hope there isn't a label limit

[nixpkgs](https://github.com/NixOS/nixpkgs/labels) currently has 166 labels so I don't think that will be an issue.

**Comment by ghostx31** [comment]
I was looking into the automation stuff for the READMEs and trying to understand our automation goal.
- Do we want to only automate the main README so that any new userstyle we add gets added automatically to the list and keep the content of the userstyle README upto the userstyle maintainer? This would mean that we need to create a template for userstyles.
- Or do we also want to automate the userstyle READMEs since most of them are going to be the same except the display images. Of course, we can add additional checks for some specific userstyles like GitHub which need additional steps to use. This might be counterproductive. winston already mentioned that we can have additional steps for some userstyles mentioned in the main README itself. 
Would appreciate some light on this.

**Comment by rubyowo** [comment]
I can do the first TODO, however i need clarification.
Should the new uri point to the rfc, or the normal org?

**Comment by sgoudham** [comment]
Closing in favour of a [project board](https://github.com/orgs/catppuccin/projects/14).
